pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                script {
                    // Force the use of the GitHub PAT for authentication
                    checkout([$class: 'GitSCM', 
                              branches: [[name: '*/main']], 
                              extensions: [[$class: 'CleanBeforeCheckout']], 
                              userRemoteConfigs: [[
                                  url: 'https://github.com/AnunukemSam/version-control-projects.git', 
                                  credentialsId: 'GitHub-PAT'  // Use the credentials ID
                              ]]])
                }
            }
        }
        stage('Build') {
            steps {
                echo 'Building the website...'
            }
        }
        stage('Test') {
            steps {
                echo 'Running tests...'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying website...'
                sh 'cp -r * /var/www/html'
            }
        }
    }
}
 
