pipeline {
    agent any
    stages {
        stage('Clone Repository') {
            steps {
                checkout scm
            }
        }
        stage('Install Dependencies') {
            steps {
                script {
                    sh """
                        python3 -m venv venv
                        source venv/bin/activate
                        pip install --upgrade pip
                        pip install -r src/requirements.txt
                    """
                }
            }
        }
        stage('Run Tests') {
            steps {
                script {
                    sh """
                        source venv/bin/activate
                        pytest src/tests
                    """
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    sh """
                        docker build -t search-app .
                    """
                }
            }
        }
        stage('Run Docker Container') {
            steps {
                script {
                    sh """
                        docker run -d -p 5000:5000 search-app
                    """
                }
            }
        }
    }
}
 
